version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node.js version 20 ..."
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist  # <<-- this must match your actual output folder
  files:
    - '**/*'
